/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sp4_console_Malki_Thibault;

/**
 *
 * @author saidm
 */
public class fenetreDejeu extends javax.swing.JFrame {

    Joueur ListeJoueurs[] = new Joueur[2];
    Joueur joueurCourant;
    Grille grilleJeu = new Grille();

    /**
     * Creates new form fenetreDejeu
     */
    public fenetreDejeu() {
        initComponents();
        panneauinfojoueurs.setVisible(false);
        panneauinfopartie.setVisible(false);

        for (int i = 5; i >= 0; i--) {
            for (int j = 0; j < 7; j++) {
                CelluleGraphique cellGraph = new CelluleGraphique(grilleJeu.CellulesJeu[i][j]);
                panneaugrille.add(cellGraph);

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneauinfojoueurs = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        panneaucreapart = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btn_col_1 = new javax.swing.JButton();
        btn_col_2 = new javax.swing.JButton();
        btn_col_3 = new javax.swing.JButton();
        btn_col_4 = new javax.swing.JButton();
        btn_col_5 = new javax.swing.JButton();
        btn_col_6 = new javax.swing.JButton();
        btn_col_7 = new javax.swing.JButton();
        panneauinfopartie = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_jcourant = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        panneaugrille = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneauinfojoueurs.setBackground(new java.awt.Color(204, 255, 204));
        panneauinfojoueurs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("INFO JOUEURS :");
        panneauinfojoueurs.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 14, 90, 30));

        jLabel4.setText("Joueur 2 :");
        panneauinfojoueurs.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setText("couleur :");
        panneauinfojoueurs.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel6.setText("desintegrateurs :");
        panneauinfojoueurs.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel7.setText("nombrejoueur2");
        panneauinfojoueurs.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        jLabel8.setText("couleurjoueur2");
        panneauinfojoueurs.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jLabel9.setText("nbr desintegrateur");
        panneauinfojoueurs.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));
        panneauinfojoueurs.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 280, 0));

        jLabel10.setText("Joueur 1 :");
        panneauinfojoueurs.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel11.setText("couleur :");
        panneauinfojoueurs.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel12.setText("desintegrateurs :");
        panneauinfojoueurs.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel13.setText("nombrejoueur1");
        panneauinfojoueurs.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        jLabel14.setText("couleurjoueur1");
        panneauinfojoueurs.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jLabel15.setText("nbr desintegrateur");
        panneauinfojoueurs.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));
        panneauinfojoueurs.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 330, 10));

        jLabel18.setText("Joueur 2 :");
        panneauinfojoueurs.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        getContentPane().add(panneauinfojoueurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 320, 240));

        panneaucreapart.setBackground(new java.awt.Color(204, 255, 204));
        panneaucreapart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nom Joueur 1");
        panneaucreapart.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 30));

        jLabel2.setText("Nom Joueur 2 ");
        panneaucreapart.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 64, 80, 20));

        jTextField1.setText("jTextField1");
        panneaucreapart.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 110, 30));

        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        panneaucreapart.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 110, 30));

        jButton1.setText("DEMARER PARTIE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panneaucreapart.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 180, 30));

        getContentPane().add(panneaucreapart, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 320, 150));

        btn_col_1.setText("1");
        btn_col_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        btn_col_2.setText("2");
        btn_col_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        btn_col_3.setText("3");
        getContentPane().add(btn_col_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        btn_col_4.setText("4");
        getContentPane().add(btn_col_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        btn_col_5.setText("5");
        getContentPane().add(btn_col_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        btn_col_6.setText("6");
        getContentPane().add(btn_col_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        btn_col_7.setText("7");
        getContentPane().add(btn_col_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, -1, -1));

        panneauinfopartie.setBackground(new java.awt.Color(204, 255, 204));
        panneauinfopartie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setText("INFO Jeu  :");
        panneauinfopartie.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 14, 90, 30));

        jLabel17.setText("Joueur Courant");
        panneauinfopartie.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        lbl_jcourant.setText("nomJoueur");
        panneauinfopartie.add(lbl_jcourant, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 100, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane1.setViewportView(jTextArea2);

        panneauinfopartie.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 270, -1));

        getContentPane().add(panneauinfopartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, 310, 180));

        panneaugrille.setBackground(new java.awt.Color(255, 255, 255));
        panneaugrille.setLayout(new java.awt.GridLayout(6, 7));
        getContentPane().add(panneaugrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 672, 576));

        setBounds(0, 0, 1044, 702);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        panneauinfojoueurs.setVisible(true);
        panneauinfopartie.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_col_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_col_1ActionPerformed

    private void btn_col_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_col_2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetreDejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetreDejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetreDejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetreDejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetreDejeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_col_1;
    private javax.swing.JButton btn_col_2;
    private javax.swing.JButton btn_col_3;
    private javax.swing.JButton btn_col_4;
    private javax.swing.JButton btn_col_5;
    private javax.swing.JButton btn_col_6;
    private javax.swing.JButton btn_col_7;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbl_jcourant;
    private javax.swing.JPanel panneaucreapart;
    private javax.swing.JPanel panneaugrille;
    private javax.swing.JPanel panneauinfojoueurs;
    private javax.swing.JPanel panneauinfopartie;
    // End of variables declaration//GEN-END:variables
}
